### ISSUE TITLE
Getting Started: How to begin an internal conversation?

### ISSUE THREAD

**Issue by MarcoWel** [LJPc-solutions/freescout-internal-conversations-module#6]
Thank you for this module @Lars- !

I have installed it, but I cannot see how I can start an internal conversation on a ticket?

Maybe I am too dumb, but a few words or a screenshot in the module readme would help getting started! 👍

**Comment by Lars-** [comment]
Hi @MarcoWel, simply start a new conversation. Then there are three buttons instead of two:
![image](https://github.com/LJPc-solutions/freescout-internal-conversations-module/assets/5690934/cf4bc7ab-eb56-4953-8f58-45cf3a344093)

The last one is for internal conversations. 

I will add "Updating the readme with screenshots" to my todo list 🙂
